WITH
  all_recipients AS (
    SELECT
      recipient
    FROM
      attestationstation_v1_optimism.EAS_evt_Attested
    UNION
    SELECT
      recipient
    FROM
      attestationstation_v1_base.EAS_evt_Attested
    UNION
    SELECT
      recipient
    FROM
      attestationstation_v1_linea.EAS_evt_Attested
    UNION
    SELECT
      recipient
    FROM
      arbitrum_eas_arbitrum.EAS_evt_Attested
    UNION
    SELECT
      recipient
    FROM
      polygon_eas_polygon.EAS_evt_Attested
    UNION
    SELECT
      recipient
    FROM
      ethereum_attestation_service_ethereum.EAS_evt_Attested
    UNION
    SELECT
      recipient
    FROM
      eas_scroll.EAS_evt_Attested
    UNION
    SELECT
      recipient
    FROM
      attestationstation_v1_zksync.EAS_evt_Attested
  )
SELECT
  COUNT(DISTINCT recipient) AS "Total Recipients"
FROM
  all_recipients